server: # 服务端口
  port: 10001
spring:
  application: # 应用名字，eureka 会根据它作为服务id
    name: spring-gateway-service
  #springbootAdmin
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: chenying521
  ## api网关
  cloud:
    gateway:
      routes:
        #监控平台
        - id: system-web
          uri: lb://biz-system-web
          predicates:
            - Path=/system/api/**
          filters:
            - PrefixPath=/
        #监控平台
        - id: business-web
          uri: lb://biz-business-web
          predicates:
            - Path=/business/api/**
          filters:
            - PrefixPath=/
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
        add-to-simple-url-handler-mapping: true

# eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  config: classpath:log4j2.xml
  max-size: 1024M
  max-history: 15
  level:
    root: info
  file:
    name: spring-gateway-service

#springbootAdmin
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"