## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 7071
  session-timeout: 2592000  # 单位: 秒. <= 30 * 24 * 60 * 60


online: true
spring:
  application:
    name: biz-system-web
  #springbootAdmin
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: chenying521
  ### redis注册信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 300
  main:
    allow-bean-definition-overriding: true
#日志
logging:
  config: classpath:log4j2.xml
  file:
    name: biz-system-web
  max-size: 1024M
  max-history: 15
  level:
    root: info

# eureka 配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    register-with-eureka: true
    fetch-registry: true
 #设置超时时间
feign:
  client:
    default-config: default
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
#springbootAdmin
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"