## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 6080
  session-timeout: 2592000  # 单位: 秒. <= 30 * 24 * 60 * 60


spring:
  application:
    name: biz-syncData-web
  #springbootAdmin
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: chenying521
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    generate-ddl: true


  datasource: #database
    #primary:  # 本地数据库
    #  name: WS #数据库名称，oracle必须使用大写
    #  jdbc-url: jdbc:oracle:thin:@192.168.3.10:1521:orcl
    #  username: ws
    #  password: 123456
    #  type: oracle #数据库类型，

    secondary:  # 本地数据库
      name: smx #数据库名称，mysql使用小写
      jdbc-url: jdbc:mysql://localhost:3306/smx?useUnicode=true&amp;characterEncoding=UTF8
      username: root
      password: ''
      type: mysql #数据库类型
    primary:  # 同步目标数据库
      name: smx_01
      jdbc-url: jdbc:mysql://localhost:3306/smx_01?useUnicode=true&amp;characterEncoding=UTF8
      username: root
      password: ''
      type: mysql

   # secondary:  # 本地数据库
   #   name: WS
   #   jdbc-url: jdbc:oracle:thin:@192.168.3.11:1521:orcl
   #   username: ws
   #   password: 123456
   #   type: oracle
#日志
logging:
  config: classpath:log4j2.xml
  file:
    name: biz-syncData-web
  max-size: 1024M
  max-history: 15
  level:
    root: info

# eureka 配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    register-with-eureka: true
    fetch-registry: true
  #设置超时时间
feign:
  client:
    default-config: default
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
#springbootAdmin
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"